import {
  Card,
  Image,
  Text,
  Badge,
  Button,
  Group,
  Container,
  Grid,
  Title,
  Anchor,
} from '@mantine/core';
import { RiGithubFill } from 'react-icons/ri';
import { SiVercel, SiNetlify } from 'react-icons/si';
import useStyles from './Work.styles';

export function Work() {
  const { classes } = useStyles();
  return (
    <Container className={classes.workSection} id="work">
      <Title className={classes.heading} order={2} size="h1">
        My work
      </Title>
      <Grid gutter="xl" gutterXl={50}>
        <Grid.Col sm={6}>
          <Card shadow="xl" padding="lg" radius="xl">
            <Card.Section className={classes.cardBg}>
              <Image src="/wunderground.avif" height={400} alt="Wünderground" />
            </Card.Section>

            <Group position="apart" mt="lg" mb="md">
              <Title order={3} size="h3" weight={500}>
                Wünderground
              </Title>
              <Group position="right" spacing="xs">
                <Badge color="cyan" variant="light">
                  NextJs
                </Badge>
                <Badge color="cyan" variant="light">
                  Tailwind
                </Badge>
                <Badge color="cyan" variant="light">
                  Sanity
                </Badge>
              </Group>
            </Group>

            <Text size="md" color="dimmed">
              Blog website with all content generated by AI.
            </Text>
            <Group>
              <Anchor href="https://github.com/martinbolsnes/wunderground-blog">
                <Button
                  leftIcon={<RiGithubFill />}
                  variant="outline"
                  color="teal"
                  mt="md"
                  radius="lg"
                >
                  Github repo
                </Button>
              </Anchor>
              <Anchor href="https://wunderground-blog.vercel.app/">
                <Button leftIcon={<SiVercel />} variant="light" color="teal" mt="md" radius="lg">
                  Visit site
                </Button>
              </Anchor>
            </Group>
          </Card>
        </Grid.Col>
        <Grid.Col sm={6}>
          <Card shadow="xl" padding="lg" radius="xl" withBorder>
            <Card.Section className={classes.cardBg}>
              <Image src="/weather-app.avif" height={400} alt="Weather App" />
            </Card.Section>

            <Group position="apart" mt="lg" mb="md">
              <Title order={3} size="h3" weight={500}>
                Weather app
              </Title>
              <Group position="right">
                <Badge color="cyan" variant="light">
                  NextJs
                </Badge>
                <Badge color="cyan" variant="light">
                  Tailwind
                </Badge>
              </Group>
            </Group>

            <Text size="md" color="dimmed">
              Current weather with OpenweatherMap API
            </Text>

            <Group>
              <Anchor href="https://github.com/martinbolsnes/weather-app">
                <Button
                  leftIcon={<RiGithubFill />}
                  variant="outline"
                  color="teal"
                  mt="md"
                  radius="lg"
                >
                  Github repo
                </Button>
              </Anchor>
              <Anchor href="https://weather-app-smoky-omega.vercel.app/">
                <Button leftIcon={<SiVercel />} variant="light" color="teal" mt="md" radius="lg">
                  Visit site
                </Button>
              </Anchor>
            </Group>
          </Card>
        </Grid.Col>
        <Grid.Col sm={6}>
          <Card shadow="xl" padding="lg" radius="xl" withBorder>
            <Card.Section className={classes.cardBg}>
              <Image src="/holidaze.avif" height={400} alt="Holidaze" />
            </Card.Section>

            <Group position="apart" mt="lg" mb="md">
              <Title order={3} size="h3" weight={500}>
                Holidaze
              </Title>
              <Group position="right">
                <Badge color="cyan" variant="light">
                  NextJs
                </Badge>
                <Badge color="cyan" variant="light">
                  Tailwind
                </Badge>
                <Badge color="cyan" variant="light">
                  Strapi
                </Badge>
              </Group>
            </Group>

            <Text size="md" color="dimmed">
              Hotel booking website with administration pages
            </Text>

            <Group>
              <Anchor href="https://github.com/martinbolsnes/project-exam-2">
                <Button
                  leftIcon={<RiGithubFill />}
                  variant="outline"
                  color="teal"
                  mt="md"
                  radius="lg"
                >
                  Github repo
                </Button>
              </Anchor>
              <Anchor href="https://project-exam-2-five.vercel.app/">
                <Button leftIcon={<SiVercel />} variant="light" color="teal" mt="md" radius="lg">
                  Visit site
                </Button>
              </Anchor>
            </Group>
          </Card>
        </Grid.Col>
        <Grid.Col sm={6}>
          <Card shadow="xl" padding="lg" radius="xl" withBorder>
            <Card.Section className={classes.cardBg}>
              <Image src="/amenity.png" height={400} alt="amenity" />
            </Card.Section>

            <Group position="apart" mt="lg" mb="md">
              <Title order={3} size="h3" weight={500}>
                amenity.
              </Title>
              <Group position="right">
                <Badge color="cyan" variant="light">
                  JavaScript
                </Badge>
                <Badge color="cyan" variant="light">
                  Bootstrap
                </Badge>
                <Badge color="cyan" variant="light">
                  Strapi
                </Badge>
              </Group>
            </Group>

            <Text size="md" color="dimmed">
              Ecommerce website with administration pages
            </Text>

            <Group>
              <Anchor href="https://github.com/martinbolsnes/semester-project-2">
                <Button
                  leftIcon={<RiGithubFill />}
                  variant="outline"
                  color="teal"
                  mt="md"
                  radius="lg"
                >
                  Github repo
                </Button>
              </Anchor>
              <Anchor href="https://semester-project2-8fe85f.netlify.app/">
                <Button leftIcon={<SiNetlify />} variant="light" color="teal" mt="md" radius="lg">
                  Visit site
                </Button>
              </Anchor>
            </Group>
          </Card>
        </Grid.Col>
      </Grid>
    </Container>
  );
}
